[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"


remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@chainlink/=lib/chainlink-local/src/"
]



